# Generated by Django 2.1.5 on 2022-12-02 11:21

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='模块名字')),
                ('img', models.CharField(max_length=256, verbose_name='模块图标')),
                ('title', models.CharField(max_length=15, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, help_text='可选', max_length=256, verbose_name='副标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('is_show', models.BooleanField(default=True, verbose_name='正式发布')),
            ],
            options={
                'verbose_name': '关于公司',
                'verbose_name_plural': '关于公司',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.IntegerField(choices=[(1, '首页'), (2, '技术服务'), (3, '行业客户'), (4, '成功案例'), (5, '升级日志'), (6, '关于软诚')], verbose_name='菜单')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('desc1', models.CharField(blank=True, default='', help_text='可选项，最多15个字符', max_length=15, verbose_name='描述1')),
                ('desc2', models.CharField(blank=True, default='', help_text='可选项，建议不超过20个字符', max_length=20, verbose_name='描述2')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('is_use', models.BooleanField(default=True, verbose_name='在用？')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='网址')),
                ('img', models.ImageField(upload_to='pictures/case/%Y/%m/%d', verbose_name='展示图片')),
                ('abstract', models.TextField(blank=True, help_text='可选项，最多54个字符', max_length=54, null=True, verbose_name='摘要')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门')),
                ('is_publish', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '案例',
                'verbose_name_plural': '案例',
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='案例类别名字')),
                ('intro', models.TextField(blank=True, default='', verbose_name='案例类别简介')),
                ('nav_display', models.BooleanField(default=True, verbose_name='导航显示')),
                ('home_display', models.BooleanField(default=True, verbose_name='首页显示')),
            ],
            options={
                'verbose_name': '案例类别',
                'verbose_name_plural': '案例类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('img', models.ImageField(upload_to='pictures/customer/%Y/%m/%d', verbose_name='展示图片')),
                ('slug', models.CharField(max_length=256, unique=True, verbose_name='网址')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('is_publish', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='客户类别名字')),
                ('intro', models.TextField(blank=True, default='', verbose_name='客户类别简介')),
                ('nav_display', models.BooleanField(default=True, verbose_name='导航显示')),
                ('home_display', models.BooleanField(default=True, verbose_name='首页显示')),
            ],
            options={
                'verbose_name': '客户类别',
                'verbose_name_plural': '客户类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('post_time', models.DateTimeField(verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='变量标题')),
                ('value', models.CharField(blank=True, max_length=256, verbose_name='变量值')),
                ('var', models.CharField(max_length=256, verbose_name='变量名')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='SettingsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='分组名')),
            ],
            options={
                'verbose_name': '配置分组',
                'verbose_name_plural': '配置分组',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='settingsgroup',
            field=models.ForeignKey(on_delete=None, to='app.SettingsGroup', verbose_name='分组'),
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.ForeignKey(on_delete=None, to='app.CustomerType', verbose_name='案例类别'),
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CaseType', verbose_name='案例类别'),
        ),
    ]
