# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '案例', 'verbose_name_plural': '案例'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AddField(
            model_name='case',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='热门'),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='intro',
            field=models.TextField(blank=True, default='', verbose_name='案例类别简介'),
        ),
    ]
