# Generated by Django 2.1.5 on 2022-12-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='网址'),
        ),
    ]
