# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180517_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customertype',
            name='slug',
        ),
    ]
