# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180517_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='column',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='customertype',
            name='intro',
            field=models.TextField(blank=True, default='', verbose_name='客户类别简介'),
        ),
    ]
