# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180517_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='published',
            new_name='is_publish',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='published',
            new_name='is_publish',
        ),
        migrations.AlterField(
            model_name='case',
            name='abstract',
            field=models.CharField(blank=True, help_text='可选项，最多54个字符', max_length=54, null=True, verbose_name='摘要'),
        ),
    ]
