# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-18 15:50
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180517_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名字')),
                ('img', models.ImageField(upload_to='pictures/about/%Y/%m/%d', verbose_name='图标')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '关于公司',
                'verbose_name_plural': '关于公司',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='变量标题')),
                ('value', models.CharField(max_length=256, verbose_name='变量值')),
                ('var', models.CharField(max_length=256, verbose_name='变量名')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='SettingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='分组名')),
            ],
            options={
                'verbose_name': '配置分组',
                'verbose_name_plural': '配置分组',
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='abstract',
            field=models.TextField(blank=True, help_text='可选项，最多54个字符', max_length=54, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='case',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间'),
        ),
        migrations.AddField(
            model_name='setting',
            name='settinggroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SettingGroup', verbose_name='分组'),
        ),
    ]
