# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-18 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180518_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
        migrations.RenameModel(
            old_name='SettingGroup',
            new_name='SettingsGroup',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='settinggroup',
            new_name='settingsgroup',
        ),
    ]
