# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180522_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '系统公告', 'verbose_name_plural': '系统公告'},
        ),
        migrations.AddField(
            model_name='about',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='正式发布'),
        ),
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.CharField(blank=True, help_text='可选', max_length=256, verbose_name='副标题'),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='', max_length=15, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.CharField(max_length=256, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=256, verbose_name='模块名字'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post_time',
            field=models.DateTimeField(verbose_name='发送时间'),
        ),
    ]
