# Generated by Django 2.0 on 2022-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180529_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.CharField(max_length=256, verbose_name='模块图标'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.ForeignKey(on_delete=None, to='app.CustomerType', verbose_name='案例类别'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='settingsgroup',
            field=models.ForeignKey(on_delete=None, to='app.SettingsGroup', verbose_name='分组'),
        ),
    ]
