# Generated by Django 2.1.5 on 2022-12-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价')),
                ('password', models.CharField(max_length=20, verbose_name='解压密码')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_no', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('pay_method', models.CharField(choices=[('2', '微信支付'), ('1', '支付宝')], default='1', max_length=5, verbose_name='支付方式')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('1', '未支付'), ('2', '已支付'), ('3', '订单信息出现问题'), ('4', '已完成')], default='1', max_length=5, verbose_name='订单状态')),
                ('trade_no', models.CharField(default='', max_length=128, verbose_name='支付编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单',
                'db_table': 'order',
            },
        ),
    ]
