# Generated by Django 2.1.5 on 2022-12-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, verbose_name='订单编号')),
                ('reason', models.CharField(choices=[('1', '无效卡密'), ('2', '虚假商品'), ('3', '非法商品'), ('4', '不能购买'), ('5', '其它投诉')], default='1', max_length=1, verbose_name='举报原因')),
                ('email', models.EmailField(max_length=50, verbose_name='联系邮箱')),
                ('alipay_no', models.CharField(max_length=50, verbose_name='收款账号(支付宝)')),
                ('content', models.TextField(max_length=250, verbose_name='投诉详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '投诉信箱',
                'verbose_name_plural': '投诉信箱',
            },
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.CharField(choices=[('1', '支付宝支付'), ('2', '微信支付')], default='1', max_length=5, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.CharField(choices=[('1', '未支付'), ('2', '已支付'), ('3', '订单信息出现问题'), ('4', '已完成'), ('5', '已退款')], default='1', max_length=5, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='支付编号'),
        ),
    ]
